-- Human-friendly, unique ticket number per Sales Hub request (the uuid id
-- isn't something you can read out loud or search for). Formatted in the UI
-- as "SH-<ticket_no>".
alter table marketing_requests add column if not exists ticket_no bigint generated by default as identity;
create unique index if not exists marketing_requests_ticket_no_idx on marketing_requests (ticket_no);
