# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "ea4efb8ebc1601ef6ee695cf83aa32eb"
name = "Brand Dashboard"
application_url = "https://example.com"
embedded = true

[webhooks]
api_version = "2026-04"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
use_legacy_install_flow = false
scopes = "read_all_orders,read_analytics,read_checkouts,read_customers,read_price_rules,write_discounts,read_inventory,write_orders,write_products,write_shipping,write_content,write_theme_code,write_themes"
optional_scopes = [ ]

[auth]
redirect_urls = [ "http://localhost:8765" ]
