"use client";

import { useEffect, useMemo, useState } from "react";
import { fmtFull } from "@/lib/format";

// Reports > D2C Weekly — the automated Sunday-7pm Shopify report across every
// brand website, styled as a branded one-pager for stakeholders (Print → PDF).
// Generated by scripts/weekly_d2c_report.py; one report per Sun–Sat week.
type BrandRow = { brand: string; revenue: number; orders: number; aov: number | null; wowPct: number | null; prevRevenue: number; vs4wkPct: number | null; sharePct: number };
type Payload = {
  weekStart: string; weekEnd: string; generatedAt: string;
  totals: { revenue: number; orders: number; aov: number | null; wowPct: number | null; prevRevenue: number };
  brands: BrandRow[]; risers: BrandRow[]; fallers: BrandRow[];
  daily?: { day: string; revenue: number; orders: number }[];
  trend?: { weekStart: string; revenue: number }[];
};
type Report = { week_start: string; payload: Payload };
type BrandRef = { name: string; color: string };

const NAVY = "#132741";
const dShort = (s: string) => new Date(s + "T00:00:00").toLocaleDateString("en-AU", { day: "numeric", month: "short" });
const dow = (s: string) => new Date(s + "T00:00:00").toLocaleDateString("en-AU", { weekday: "short" });
const fmtK = (n: number) => n >= 1000 ? `$${Math.round(n / 1000)}k` : `$${n}`;
const WowPill = ({ v, light = false }: { v: number | null; light?: boolean }) => {
  if (v == null) return null;
  const up = v >= 0;
  return (
    <span className={`inline-flex items-center gap-1 text-[12px] font-bold rounded-full px-2.5 py-1 ${
      light ? (up ? "bg-emerald-400/20 text-emerald-300" : "bg-rose-400/20 text-rose-300")
            : (up ? "bg-emerald-100 text-emerald-700" : "bg-rose-100 text-rose-600")}`}>
      {up ? "▲" : "▼"} {Math.abs(v)}% WoW
    </span>
  );
};
const Delta = ({ v }: { v: number | null }) => v == null ? <span className="text-slate-300">—</span>
  : <span className={`font-semibold ${v >= 0 ? "text-emerald-600" : "text-rose-500"}`}>{v >= 0 ? "▲" : "▼"} {Math.abs(v)}%</span>;

export function D2CWeekly({ brands = [] }: { brands?: BrandRef[] }) {
  const [reports, setReports] = useState<Report[]>([]);
  const [loading, setLoading] = useState(true);
  const [needsSetup, setNeedsSetup] = useState(false);
  const [sel, setSel] = useState<string | null>(null);

  useEffect(() => {
    fetch("/api/d2c-weekly").then(r => r.json()).then(d => {
      if (d.needsSetup) setNeedsSetup(true);
      else if (d.ok) { setReports(d.reports ?? []); setSel(d.reports?.[0]?.week_start ?? null); }
    }).catch(() => {}).finally(() => setLoading(false));
  }, []);

  const report = useMemo(() => reports.find(r => r.week_start === sel)?.payload ?? null, [reports, sel]);
  const color = (name: string) => brands.find(b => b.name.toLowerCase() === name.toLowerCase())?.color ?? "#94a3b8";

  if (loading) return <div className="p-8 text-center text-sm text-gray-400">Loading…</div>;
  if (needsSetup) return <div className="bg-white rounded-2xl border border-gray-100 shadow-sm p-8 text-center text-sm text-gray-500">Run <code className="bg-gray-100 px-1 rounded">add_d2c_weekly_reports.sql</code> first.</div>;
  if (!report) return <div className="bg-white rounded-2xl border border-gray-100 shadow-sm p-8 text-center text-sm text-gray-400">No reports yet — the first one generates Sunday 7pm (or run the d2c-weekly-report workflow manually).</div>;

  const t = report.totals;
  const maxRev = Math.max(1, ...report.brands.map(b => b.revenue));
  const daily = report.daily ?? [];
  const trend = report.trend ?? [];
  const maxDaily = Math.max(1, ...daily.map(d => d.revenue));
  const maxTrend = Math.max(1, ...trend.map(w => w.revenue));

  return (
    <div className="space-y-3 max-w-[900px]">
      <div className="flex items-center justify-between gap-3 print:hidden">
        <select value={sel ?? ""} onChange={e => setSel(e.target.value)} className="text-sm border border-gray-200 rounded-lg px-3 py-2 text-slate-700 focus:outline-none focus:ring-2 focus:ring-emerald-400">
          {reports.map(r => <option key={r.week_start} value={r.week_start}>Week of {dShort(r.week_start)}</option>)}
        </select>
        <button onClick={() => window.print()} className="text-sm font-semibold text-white rounded-lg px-4 py-2" style={{ background: NAVY }}>Print / PDF</button>
      </div>

      <article className="bg-white rounded-2xl shadow-sm ring-1 ring-slate-200/70 overflow-hidden print:shadow-none print:ring-0 print:rounded-none">
        {/* Hero band */}
        <div className="px-8 py-6 text-white" style={{ background: `linear-gradient(120deg, ${NAVY}, #1d3a5f)` }}>
          <div className="flex items-start justify-between gap-4 flex-wrap">
            <div>
              <p className="text-[10px] font-bold uppercase tracking-[0.28em] text-emerald-300">Coolkidz Australia · D2C Weekly</p>
              <h1 className="text-2xl font-bold mt-1">Week {dShort(report.weekStart)} – {dShort(report.weekEnd)}</h1>
              <p className="text-[12px] text-slate-300 mt-0.5">All brand websites · Shopify · revenue ex-GST</p>
            </div>
            <div className="text-right">
              <p className="text-4xl font-bold tracking-tight">{fmtFull(t.revenue)}</p>
              <div className="mt-1.5 flex items-center gap-2 justify-end">
                <WowPill v={t.wowPct} light />
                <span className="text-[12px] text-slate-300">prev {fmtFull(t.prevRevenue)}</span>
              </div>
            </div>
          </div>
          <div className="flex gap-8 mt-5 flex-wrap">
            {[["Orders", t.orders.toLocaleString()], ["Average order", t.aov != null ? fmtFull(t.aov) : "—"], ["Brands trading", String(report.brands.length)]].map(([l, v]) => (
              <div key={l}><p className="text-[10px] uppercase tracking-[0.18em] text-slate-400">{l}</p><p className="text-xl font-bold">{v}</p></div>
            ))}
          </div>
        </div>

        <div className="px-8 py-6 space-y-6">
          {/* Trend + daily charts */}
          <div className="grid sm:grid-cols-2 gap-6">
            {trend.length > 1 && (
              <div>
                <p className="text-[10px] font-bold uppercase tracking-[0.2em] text-slate-400 mb-2">Portfolio · last {trend.length} weeks</p>
                <div className="flex items-end gap-1.5 h-28">
                  {trend.map((w, i) => {
                    const cur = i === trend.length - 1;
                    return (
                      <div key={w.weekStart} className="flex-1 flex flex-col items-center gap-1" title={`w/c ${dShort(w.weekStart)}: ${fmtFull(w.revenue)}`}>
                        <span className={`text-[9px] ${cur ? "font-bold text-slate-700" : "text-gray-400"}`}>{fmtK(w.revenue)}</span>
                        <div className={`w-full rounded-t ${cur ? "" : "opacity-45"}`} style={{ height: `${Math.max(3, (w.revenue / maxTrend) * 76)}px`, background: cur ? "#10b981" : NAVY }} />
                        <span className="text-[9px] text-gray-400">{dShort(w.weekStart).split(" ")[0]}/{new Date(w.weekStart + "T00:00:00").getMonth() + 1}</span>
                      </div>
                    );
                  })}
                </div>
              </div>
            )}
            {daily.length > 0 && (
              <div>
                <p className="text-[10px] font-bold uppercase tracking-[0.2em] text-slate-400 mb-2">This week · day by day</p>
                <div className="flex items-end gap-1.5 h-28">
                  {daily.map(d => (
                    <div key={d.day} className="flex-1 flex flex-col items-center gap-1" title={`${dow(d.day)} ${dShort(d.day)}: ${fmtFull(d.revenue)} · ${d.orders} orders`}>
                      <span className="text-[9px] text-gray-400">{fmtK(d.revenue)}</span>
                      <div className="w-full rounded-t bg-emerald-400" style={{ height: `${Math.max(3, (d.revenue / maxDaily) * 76)}px` }} />
                      <span className="text-[9px] text-gray-400">{dow(d.day)}</span>
                    </div>
                  ))}
                </div>
              </div>
            )}
          </div>

          {/* Movers */}
          {(report.risers.length > 0 || report.fallers.length > 0) && (
            <div className="grid sm:grid-cols-2 gap-4">
              <div className="rounded-xl border border-emerald-100 bg-emerald-50/60 px-4 py-3">
                <p className="text-[10px] font-bold uppercase tracking-[0.2em] text-emerald-700 mb-1.5">▲ Risers</p>
                {report.risers.length ? report.risers.map(b => (
                  <p key={b.brand} className="text-[13.5px] text-slate-700 flex items-center gap-2">
                    <span className="w-2 h-2 rounded-full shrink-0" style={{ background: color(b.brand) }} />
                    <strong>{b.brand}</strong> +{b.wowPct}% · {fmtFull(b.revenue)}
                  </p>
                )) : <p className="text-[12.5px] text-gray-400">None this week.</p>}
              </div>
              <div className="rounded-xl border border-rose-100 bg-rose-50/60 px-4 py-3">
                <p className="text-[10px] font-bold uppercase tracking-[0.2em] text-rose-600 mb-1.5">▼ Fallers</p>
                {report.fallers.length ? report.fallers.map(b => (
                  <p key={b.brand} className="text-[13.5px] text-slate-700 flex items-center gap-2">
                    <span className="w-2 h-2 rounded-full shrink-0" style={{ background: color(b.brand) }} />
                    <strong>{b.brand}</strong> −{Math.abs(b.wowPct!)}% · {fmtFull(b.revenue)}
                  </p>
                )) : <p className="text-[12.5px] text-gray-400">None this week.</p>}
              </div>
            </div>
          )}

          {/* Brand table */}
          <div>
            <p className="text-[10px] font-bold uppercase tracking-[0.2em] text-slate-400 mb-2">By brand</p>
            <table className="w-full text-sm">
              <thead>
                <tr className="text-[10px] uppercase tracking-wider text-gray-400 border-b border-gray-100">
                  <th className="text-left py-2">Brand</th>
                  <th className="text-right px-2 py-2">Revenue</th>
                  <th className="text-right px-2 py-2">WoW</th>
                  <th className="text-right px-2 py-2">vs 4-wk avg</th>
                  <th className="text-right px-2 py-2">Orders</th>
                  <th className="text-right px-2 py-2">AOV</th>
                  <th className="text-left pl-4 py-2 w-[22%]">Share</th>
                </tr>
              </thead>
              <tbody>
                {report.brands.map(b => (
                  <tr key={b.brand} className="border-b border-gray-50 last:border-0">
                    <td className="py-2 font-semibold text-slate-700"><span className="inline-flex items-center gap-2"><span className="w-2.5 h-2.5 rounded-full shrink-0" style={{ background: color(b.brand) }} />{b.brand}</span></td>
                    <td className="px-2 py-2 text-right font-bold text-slate-800">{fmtFull(b.revenue)}</td>
                    <td className="px-2 py-2 text-right text-[13px]"><Delta v={b.wowPct} /></td>
                    <td className="px-2 py-2 text-right text-[13px]"><Delta v={b.vs4wkPct} /></td>
                    <td className="px-2 py-2 text-right text-slate-600">{b.orders.toLocaleString()}</td>
                    <td className="px-2 py-2 text-right text-slate-600">{b.aov != null ? fmtFull(b.aov) : "—"}</td>
                    <td className="pl-4 py-2">
                      <div className="flex items-center gap-2">
                        <div className="flex-1 h-2 rounded-full bg-gray-100"><div className="h-2 rounded-full" style={{ width: `${Math.max(1.5, (b.revenue / maxRev) * 100)}%`, background: color(b.brand) }} /></div>
                        <span className="text-[11px] text-gray-400 w-11 text-right">{b.sharePct}%</span>
                      </div>
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        </div>

        <footer className="px-8 py-3 text-[9px] tracking-[0.06em] text-slate-300 flex justify-between" style={{ background: NAVY }}>
          <span>Coolkidz Australia · D2C Weekly Report · business weeks run Sunday–Saturday</span>
          <span>Generated {new Date(report.generatedAt).toLocaleString("en-AU", { day: "numeric", month: "short", hour: "numeric", minute: "2-digit" })}</span>
        </footer>
      </article>
    </div>
  );
}
