"use client";

import { useEffect, useMemo, useState } from "react";
import { fmtFull } from "@/lib/format";

// Reports > D2C Weekly — the automated Sunday-7pm Shopify report across every
// brand website. One report per business week (Sun–Sat); week picker for
// history. Generated by scripts/weekly_d2c_report.py.
type BrandRow = { brand: string; revenue: number; orders: number; aov: number | null; wowPct: number | null; prevRevenue: number; vs4wkPct: number | null; sharePct: number };
type Payload = {
  weekStart: string; weekEnd: string; generatedAt: string;
  totals: { revenue: number; orders: number; aov: number | null; wowPct: number | null; prevRevenue: number };
  brands: BrandRow[]; risers: BrandRow[]; fallers: BrandRow[];
};
type Report = { week_start: string; payload: Payload };

const dShort = (s: string) => new Date(s + "T00:00:00").toLocaleDateString("en-AU", { day: "numeric", month: "short" });
const Wow = ({ v }: { v: number | null }) => v == null ? <span className="text-slate-300">—</span>
  : <span className={v >= 0 ? "text-emerald-600" : "text-rose-500"}>{v >= 0 ? "▲" : "▼"} {Math.abs(v)}%</span>;

export function D2CWeekly() {
  const [reports, setReports] = useState<Report[]>([]);
  const [loading, setLoading] = useState(true);
  const [needsSetup, setNeedsSetup] = useState(false);
  const [sel, setSel] = useState<string | null>(null);

  useEffect(() => {
    fetch("/api/d2c-weekly").then(r => r.json()).then(d => {
      if (d.needsSetup) setNeedsSetup(true);
      else if (d.ok) { setReports(d.reports ?? []); setSel(d.reports?.[0]?.week_start ?? null); }
    }).catch(() => {}).finally(() => setLoading(false));
  }, []);

  const report = useMemo(() => reports.find(r => r.week_start === sel)?.payload ?? null, [reports, sel]);

  if (loading) return <div className="p-8 text-center text-sm text-gray-400">Loading…</div>;
  if (needsSetup) return <div className="bg-white rounded-2xl border border-gray-100 shadow-sm p-8 text-center text-sm text-gray-500">Run <code className="bg-gray-100 px-1 rounded">add_d2c_weekly_reports.sql</code> first.</div>;
  if (!report) return <div className="bg-white rounded-2xl border border-gray-100 shadow-sm p-8 text-center text-sm text-gray-400">No reports yet — the first one generates Sunday 7pm (or run the d2c-weekly-report workflow manually).</div>;

  const t = report.totals;
  const maxRev = Math.max(1, ...report.brands.map(b => b.revenue));
  return (
    <div className="space-y-4 max-w-[900px]">
      <div className="flex flex-wrap items-end justify-between gap-3">
        <div>
          <h1 className="text-xl font-bold text-slate-800">D2C Weekly</h1>
          <p className="text-sm text-gray-400">All brand websites · business week {dShort(report.weekStart)} – {dShort(report.weekEnd)} · auto-generated Sunday 7pm</p>
        </div>
        <select value={sel ?? ""} onChange={e => setSel(e.target.value)} className="text-sm border border-gray-200 rounded-lg px-3 py-2 text-slate-700 focus:outline-none focus:ring-2 focus:ring-emerald-400">
          {reports.map(r => <option key={r.week_start} value={r.week_start}>Week of {dShort(r.week_start)}</option>)}
        </select>
      </div>

      <div className="grid grid-cols-2 sm:grid-cols-4 gap-3">
        <div className="bg-white rounded-2xl border border-gray-100 shadow-sm p-4"><p className="text-[11px] uppercase tracking-wider text-gray-400">D2C revenue</p><p className="text-2xl font-bold text-slate-800">{fmtFull(t.revenue)}</p><p className="text-[12px] mt-0.5"><Wow v={t.wowPct} /> <span className="text-gray-400">vs {fmtFull(t.prevRevenue)}</span></p></div>
        <div className="bg-white rounded-2xl border border-gray-100 shadow-sm p-4"><p className="text-[11px] uppercase tracking-wider text-gray-400">Orders</p><p className="text-2xl font-bold text-slate-800">{t.orders.toLocaleString()}</p></div>
        <div className="bg-white rounded-2xl border border-gray-100 shadow-sm p-4"><p className="text-[11px] uppercase tracking-wider text-gray-400">AOV</p><p className="text-2xl font-bold text-slate-800">{t.aov != null ? fmtFull(t.aov) : "—"}</p></div>
        <div className="bg-white rounded-2xl border border-gray-100 shadow-sm p-4"><p className="text-[11px] uppercase tracking-wider text-gray-400">Brands trading</p><p className="text-2xl font-bold text-slate-800">{report.brands.length}</p></div>
      </div>

      {(report.risers.length > 0 || report.fallers.length > 0) && (
        <div className="grid sm:grid-cols-2 gap-3">
          {report.risers.length > 0 && (
            <div className="rounded-2xl border border-emerald-100 bg-emerald-50/50 p-4">
              <p className="text-[11px] font-bold uppercase tracking-wider text-emerald-700 mb-1.5">Risers</p>
              {report.risers.map(b => <p key={b.brand} className="text-[13.5px] text-slate-700"><strong>{b.brand}</strong> ▲ {b.wowPct}% · {fmtFull(b.revenue)}</p>)}
            </div>
          )}
          {report.fallers.length > 0 && (
            <div className="rounded-2xl border border-rose-100 bg-rose-50/50 p-4">
              <p className="text-[11px] font-bold uppercase tracking-wider text-rose-600 mb-1.5">Fallers</p>
              {report.fallers.map(b => <p key={b.brand} className="text-[13.5px] text-slate-700"><strong>{b.brand}</strong> ▼ {Math.abs(b.wowPct!)}% · {fmtFull(b.revenue)}</p>)}
            </div>
          )}
        </div>
      )}

      <div className="bg-white rounded-2xl border border-gray-100 shadow-sm overflow-x-auto">
        <table className="w-full text-sm">
          <thead>
            <tr className="text-[11px] uppercase tracking-wider text-gray-400 border-b border-gray-100">
              <th className="text-left px-4 py-2.5">Brand</th>
              <th className="text-right px-3 py-2.5">Revenue</th>
              <th className="text-right px-3 py-2.5">WoW</th>
              <th className="text-right px-3 py-2.5">vs 4-wk avg</th>
              <th className="text-right px-3 py-2.5">Orders</th>
              <th className="text-right px-3 py-2.5">AOV</th>
              <th className="text-left px-4 py-2.5 w-[24%]">Share</th>
            </tr>
          </thead>
          <tbody>
            {report.brands.map(b => (
              <tr key={b.brand} className="border-b border-gray-50 last:border-0">
                <td className="px-4 py-2 font-semibold text-slate-700">{b.brand}</td>
                <td className="px-3 py-2 text-right font-semibold text-slate-800">{fmtFull(b.revenue)}</td>
                <td className="px-3 py-2 text-right"><Wow v={b.wowPct} /></td>
                <td className="px-3 py-2 text-right"><Wow v={b.vs4wkPct} /></td>
                <td className="px-3 py-2 text-right text-slate-600">{b.orders.toLocaleString()}</td>
                <td className="px-3 py-2 text-right text-slate-600">{b.aov != null ? fmtFull(b.aov) : "—"}</td>
                <td className="px-4 py-2">
                  <div className="flex items-center gap-2">
                    <div className="flex-1 h-1.5 rounded-full bg-gray-100"><div className="h-1.5 rounded-full bg-emerald-400" style={{ width: `${(b.revenue / maxRev) * 100}%` }} /></div>
                    <span className="text-[11px] text-gray-400 w-10 text-right">{b.sharePct}%</span>
                  </div>
                </td>
              </tr>
            ))}
          </tbody>
        </table>
      </div>
      <p className="text-[11px] text-gray-400">Generated {new Date(report.generatedAt).toLocaleString("en-AU", { weekday: "short", day: "numeric", month: "short", hour: "numeric", minute: "2-digit" })} · source: Shopify via brand_daily (ex-GST). Business weeks run Sunday–Saturday.</p>
    </div>
  );
}
