"use client";

import { useEffect, useState } from "react";
import { fmtFull } from "@/lib/format";

type Code = {
  brand_id: number; code: string; usage_count: number; value_type: string | null; value: number | null;
  starts_at: string | null; ends_at: string | null; status: "active" | "expired" | "scheduled";
};
type Brand = { id: number; name: string };

const dMY = (s: string | null) => s ? new Date(s + "T00:00:00").toLocaleDateString("en-AU", { day: "numeric", month: "short", year: "numeric" }) : "—";
const STATUS_CLS: Record<Code["status"], string> = {
  active: "bg-emerald-100 text-emerald-700", expired: "bg-gray-100 text-gray-500", scheduled: "bg-amber-100 text-amber-700",
};

export function DiscountCodesTab({ brands }: { brands: Brand[] }) {
  const [codes, setCodes] = useState<Code[] | null>(null);
  const [needsSetup, setNeedsSetup] = useState(false);
  const [q, setQ] = useState("");
  const [statusFilter, setStatusFilter] = useState<"active" | "all">("active");

  useEffect(() => {
    fetch("/api/discount-codes", { cache: "no-store" }).then(r => r.json()).then(d => {
      if (d.needsSetup) setNeedsSetup(true); else if (d.ok) setCodes(d.codes ?? []);
    }).catch(() => {});
  }, []);

  const brandName = (id: number) => brands.find(b => b.id === id)?.name ?? `Brand ${id}`;

  if (needsSetup) return (
    <div className="bg-white rounded-2xl border border-gray-100 shadow-sm p-8 text-center text-sm text-gray-500">
      Run <code className="bg-gray-100 px-1 rounded">add_shop_discount_codes_classification.sql</code> in Supabase, then the next sync fills this in.
    </div>
  );
  if (codes === null) return <div className="bg-white rounded-2xl border border-gray-100 shadow-sm p-8 text-center text-sm text-gray-400">Loading…</div>;

  const filtered = codes
    .filter(c => statusFilter === "all" || c.status !== "expired")
    .filter(c => !q || c.code.toLowerCase().includes(q.toLowerCase()))
    .sort((a, b) => (a.status === "active" ? 0 : 1) - (b.status === "active" ? 0 : 1) || b.usage_count - a.usage_count);

  return (
    <div className="space-y-4">
      <div className="bg-white rounded-2xl border border-gray-100 shadow-sm p-5">
        <div className="flex items-center justify-between flex-wrap gap-3 mb-1">
          <div>
            <h2 className="text-[11px] font-bold uppercase tracking-[0.18em] text-slate-600">Discount codes</h2>
            <p className="text-xs text-gray-400 mt-0.5">
              Main promotional codes only — individual/one-off codes (single-use, or bulk-generated by an affiliate or loyalty app) are excluded.
            </p>
          </div>
          <div className="flex items-center gap-2">
            <button onClick={() => setStatusFilter("active")} className={`text-[11px] font-semibold px-2.5 py-1 rounded-full border ${statusFilter === "active" ? "bg-slate-800 text-white border-slate-800" : "bg-white text-gray-500 border-gray-200"}`}>Active only</button>
            <button onClick={() => setStatusFilter("all")} className={`text-[11px] font-semibold px-2.5 py-1 rounded-full border ${statusFilter === "all" ? "bg-slate-800 text-white border-slate-800" : "bg-white text-gray-500 border-gray-200"}`}>Include expired</button>
            <input value={q} onChange={e => setQ(e.target.value)} placeholder="Search a code…" className="text-sm border border-gray-200 rounded-lg px-3 py-1.5 focus:outline-none focus:ring-2 focus:ring-emerald-300" />
          </div>
        </div>
        {filtered.length === 0 ? (
          <p className="text-sm text-gray-400 py-6 text-center">No {statusFilter === "active" ? "active " : ""}main codes found.</p>
        ) : (
          <table className="w-full text-sm mt-3">
            <thead>
              <tr className="text-[11px] text-gray-400 uppercase tracking-wide text-left border-b border-gray-100">
                <th className="font-medium py-1.5">Code</th><th className="font-medium">Brand</th><th className="font-medium">Status</th>
                <th className="font-medium text-right">Deal</th><th className="font-medium">Starts</th><th className="font-medium">Ends</th>
                <th className="font-medium text-right">Uses</th>
              </tr>
            </thead>
            <tbody>
              {filtered.map(c => (
                <tr key={`${c.brand_id}-${c.code}`} className="border-b border-gray-50 text-slate-700">
                  <td className="py-1.5 font-mono text-[12.5px] font-semibold">{c.code}</td>
                  <td className="text-[12.5px] text-gray-500">{brandName(c.brand_id)}</td>
                  <td><span className={`text-[10px] font-semibold px-2 py-0.5 rounded-full ${STATUS_CLS[c.status]}`}>{c.status}</span></td>
                  <td className="text-right">{c.value ? (c.value_type === "percentage" ? `${Math.round(c.value)}%` : fmtFull(c.value)) : "—"}</td>
                  <td className="text-gray-500">{dMY(c.starts_at)}</td>
                  <td className="text-gray-500">{dMY(c.ends_at)}</td>
                  <td className="text-right font-bold">{c.usage_count.toLocaleString()}</td>
                </tr>
              ))}
            </tbody>
          </table>
        )}
      </div>
    </div>
  );
}
